[gcp_service_account]
type = "service_account"
project_id= "senior-medication-app"
private_key_id= "c4d48cf854bb3c90646d75d2910b7469ebd00884"
private_key= """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDDsAKL0Rg05qQrZK7ZpCLRs8PDr3W9hjoeMaHI0Oxl8ngdejrw4RAI87cE9gOEhfuqrDD1bO8WkXTMX6aVzlY203seE/0KWQ+91dY/KnOVNSxCZRSEZsySH1MQIXgcdLzoibhCj9+c4EJ/OH8yW1tJqtU8bDIVi1v4gULfDpvj73ufLqhlXRNX8yln9m/6sMC4xWPD+aMQc1mw
i7fLg8Lvhe86gzPNZ/sB8fRw0KEbhNRBEuSMcrbUV9Ad1FoEFU5IEF2GMVsiojRt
/HCsqZ/iP7MrkHti6bqGVoLcf9QBeAauLXKA+K0veB6oiWviVtY6Rc+AWTB/TGlh
a7rmty9xAgMBAAECggEAD8TzC5PbxMWSVLneGkVPFgGLxMzyqsVykQTUYgOuDTAb
LFrxfYBRg7sqFEED+w22AGS0ZE61PKcXl7GckcVpLq1fpkablVYkfdqJ05jG7C73
BFmza9EB6sOR9MKRtI9WutGAUwLXlQOAcFKb83Gnu1nEKcSZS6GplW7LNgDuIJHD
m1TbvZsP2O4RiTcR75knYnzP6J9BH0a+toIBEU5hBCfoVSosc/RKmyY3SLG9fwJD
un+PTmcxEnW+ZmIIpcpAMiL4WTzBdJuNo1jlBIJoemlV+UnWtrz0i4xolAwv/8SX
n/WdmeiIT3zSdt8b5vJ8Fype1nINVIGpdjbYK51BkQKBgQDjXb58hK0UYAkD9m3r
lempCrQBfiJemofovDkeUkLdBbNZV2hdjznfZNOTbdud9Qg/lCqLPNXGrQCSgcLH
tn5JdM+vp+oEs+2A6ajoXLm+1B889cx/shvqYJReGM1AVclz77k1hai7GmZBdJze
yCfdHQ/4eKS96FoN8YmvCvB5iQKBgQDcVPNM7RgYRZwCQya2/eBiYfegFF2sGF9d
plShuSsRx7N3VVHlnWgEvLhF5SH2ThCL3WEOmmtvlTPWcKbeNXSBqWZkZZZHf0Vu
SiUBLFMnN45qw6f9W/ek3E+0Nh5CF5RIF6t1ZDPCh2l7Zf5T4HHv7uhzuqyFXsdQ
eddvreZUqQKBgGSls9QFG2UAmh0R8liuNRAqd8KNZoOAXpds8s/0VDro8hqjccSw
yUqVpH8Hy4ch1/PlD+wxEuTu4mj4XhPwOfkkZ2d3qkVIrOM7DBVILsVFu0pN+Key
XV8kP6ljy0AmeZYD0XXa4/VnW0qwZ1zLN7JO0ioIpcyXVX4EpRFCg28ZAoGARuId
k/YC9mwOkLvBzMVIVt5lp95ldGQy6hIE0DKeJI42soGEY3aMbFm6fuIEVxUuRZDn
FKehQLijgK2lQX+5B63T/yCfhEjxsVWxKft0lP1OmBJyDRR1S1iFW9i9S04Cql7T
DmU6Ma8WxFg/xgRDI4mcxv6bWhzvyngoUwmDPGECgYBvS4IqiYuLJb8S1CIKEc76
ZwZxha6EZJS1OUXvLOJh5+QOpNcbwuLryOfT6uB0THbbJJ8wP+hkCeSLE2WonvFi
woEXfrViJZSw4Krm/wPP/FMdfyv6ycKLCtMwQQGeJAPQiXpHt4DfkxIljrJqqCGS
8uY8OyAB4vdltXDhkyLUDg==
-----END PRIVATE KEY-----
"""
client_email= "senior-medication-app@senior-medication-app.iam.gserviceaccount.com"
client_id= "102720993234716607497"
auth_uri= "https://accounts.google.com/o/oauth2/auth"
token_uri= "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/senior-medication-app%40senior-medication-app.iam.gserviceaccount.com"
universe_domain= "googleapis.com"
